version: '3.8'
services:
    db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: lt1414**

    php:
      build:
        context: .
      image: sf-docker/php:dev
      restart: on-failure
      environment: 
        APP_ENV: dev
        APP_DEBUG: 1
        PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE: -UTC}
      depends_on: 
        - db

    nginx:
      build:
        context: .
        target: app_nginx
      image: sf-docker/nginx:dev
      restart: on-failure
      depends_on:
        - php
      volumes:
        - ./public:/app/public:ro
      ports:
        - "8080:80"

  volumes:
    db-data:
    var:
